remote_theme: just-the-docs/just-the-docs
callouts:
  warning:
    title: Warning
    color: red
  warning:
    title: Highlight
    color: yellow
toc:
  - title: Home
    url: index.html
  - title: Demo
    url: demo.html
  - title: Controls
    url: controls.html
  - title: FAQ
    url: faq.html
  - title: Support
    url: support.html
  - title: Experimental
    subfolderitems:
      - page: Evaluate OCR Data
        url: /evaluate.html
      - page: Table Extraction - Reference
        url: /tables.html
      - page: Table Extraction - Walkthrough
        url: /tables_walkthrough.html